// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwlb7YV0iMmgR6vB3ZAsvQZD0TuRwB4P0',
    appId: '1:97249007134:web:32ec10a846bba25425400f',
    messagingSenderId: '97249007134',
    projectId: 'spacenewscore-55e6d',
    authDomain: 'spacenewscore-55e6d.firebaseapp.com',
    storageBucket: 'spacenewscore-55e6d.firebasestorage.app',
    measurementId: 'G-SCWBLZMG29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcID3qtPCAkQyJ2Ofnx8soKjoBiZF4HIE',
    appId: '1:97249007134:android:43ee1b2b6856a74325400f',
    messagingSenderId: '97249007134',
    projectId: 'spacenewscore-55e6d',
    storageBucket: 'spacenewscore-55e6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcKQyBWuMCDQJewvN2_h0boKXE97N0Jko',
    appId: '1:97249007134:ios:6310420c58248d5925400f',
    messagingSenderId: '97249007134',
    projectId: 'spacenewscore-55e6d',
    storageBucket: 'spacenewscore-55e6d.firebasestorage.app',
    iosBundleId: 'com.example.spacenewsCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcKQyBWuMCDQJewvN2_h0boKXE97N0Jko',
    appId: '1:97249007134:ios:6310420c58248d5925400f',
    messagingSenderId: '97249007134',
    projectId: 'spacenewscore-55e6d',
    storageBucket: 'spacenewscore-55e6d.firebasestorage.app',
    iosBundleId: 'com.example.spacenewsCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwlb7YV0iMmgR6vB3ZAsvQZD0TuRwB4P0',
    appId: '1:97249007134:web:bcfc00db9a2c90f625400f',
    messagingSenderId: '97249007134',
    projectId: 'spacenewscore-55e6d',
    authDomain: 'spacenewscore-55e6d.firebaseapp.com',
    storageBucket: 'spacenewscore-55e6d.firebasestorage.app',
    measurementId: 'G-6XJGLDBQX8',
  );
}
